version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      GH actions:
        dependency-type: production
  - package-ecosystem: "pip"
    directory: "/picotts/wrapper"
    schedule:
      interval: "monthly"
    groups:
      Wrapper packages:
        dependency-type: production
